# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2HF2TW4T8WLuTnZyjv3wGSWiD_4QxR_
"""

# Usually pre-installed in Colab, but safe to re-run
!pip install pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()  # choose your CSV file

df = pd.read_csv('crypto_prices_all.csv')
df.head()

df.info()

df.shape

df.describe()

df.isnull().sum()

"""# Drop the first row (it contains repeated headers like 'BTC-USD')"""

df = df.drop(0)

df.head()

"""# Convert 'Date' to datetime and sort"""

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')

"""# Select only BTC data for now (you can repeat for ETH and DOGE later)"""

btc_df = df[['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Coin']].copy()

"""# Convert numeric columns to floats

"""

for col in ['Close', 'High', 'Low', 'Open', 'Volume']:
    btc_df[col] = pd.to_numeric(btc_df[col], errors='coerce')

"""# Drop rows with missing values"""

btc_df = btc_df.dropna()

"""# ✅ Basic info after cleaning"""

print(btc_df.info())
print(btc_df.head())

"""# Save cleaned data"""

btc_df.to_csv("cleaned_btc_data.csv", index=False)

"""1️⃣ Price Trend"""

plt.figure(figsize=(10,5))
plt.plot(btc_df['Date'], btc_df['Close'])
plt.title('BTC Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.show()

"""2️⃣ Distribution"""

sns.histplot(btc_df['Close'], kde=True)
plt.title('Distribution of BTC Closing Prices')
plt.show()

"""3️⃣ Correlation"""

sns.heatmap(btc_df[['Close','High','Low','Open','Volume']].corr(), annot=True, cmap='coolwarm')
plt.title('BTC Price Feature Correlation')
plt.show()

"""# 🔵 Ethereum (ETH) Cleaning + EDA"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from google.colab import files
uploaded = files.upload()  # choose your CSV file

"""load the file"""

df = pd.read_csv("crypto_prices_all.csv")

# Create ETH dataset
eth_df = df[['Date', 'Open.1', 'High.1', 'Low.1', 'Close.1', 'Volume.1']].copy()
eth_df.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']

# Convert all numeric columns
for col in ['Open', 'High', 'Low', 'Close', 'Volume']:
    eth_df[col] = pd.to_numeric(eth_df[col], errors='coerce')

# Drop missing values
eth_df = eth_df.dropna()

# Add a coin identifier
eth_df['Coin'] = 'ETH-USD'

print("✅ Cleaned ETH data saved as 'cleaned_eth_data.csv'")
print(eth_df.head())

"""# Save cleaned ETH data"""

eth_df.to_csv('cleaned_eth_data.csv', index=False)

"""basic info"""

print(eth_df.describe())

"""Closing Price Trend"""

plt.figure(figsize=(10,5))
plt.plot(eth_df['Date'], eth_df['Close'])
plt.title('Ethereum (ETH-USD) Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price (USD)')
plt.grid(True)
plt.show()

""" Price Distribution"""

sns.histplot(eth_df['Close'], kde=True, bins=30)
plt.title('Distribution of Ethereum Closing Prices')
plt.xlabel('Closing Price (USD)')
plt.show()

""" Correlation Heatmap"""

plt.figure(figsize=(7,5))
sns.heatmap(eth_df[['Open', 'High', 'Low', 'Close', 'Volume']].corr(), annot=True, cmap='coolwarm')
plt.title('Ethereum Price Feature Correlation')
plt.show()

""" Volume vs Price Scatter"""

sns.scatterplot(x='Volume', y='Close', data=eth_df)
plt.title('Ethereum: Volume vs Closing Price')
plt.show()

"""🟡 Dogecoin (DOGE) Cleaning + EDA"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from google.colab import files
uploaded = files.upload()  # choose your CSV file

df = pd.read_csv("crypto_prices_all.csv")

# Create DOGE dataset
doge_df = df[['Date', 'Open.2', 'High.2', 'Low.2', 'Close.2', 'Volume.2']].copy()
doge_df.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']

# Convert numeric columns
for col in ['Open', 'High', 'Low', 'Close', 'Volume']:
    doge_df[col] = pd.to_numeric(doge_df[col], errors='coerce')

# Drop missing values
doge_df = doge_df.dropna()

# Add a coin identifier
doge_df['Coin'] = 'DOGE-USD'

print("✅ Cleaned DOGE data saved as 'cleaned_doge_data.csv'")
print(doge_df.head())

"""# Save cleaned DOGE data"""

doge_df.to_csv('cleaned_doge_data.csv', index=False)

"""# 1️⃣ Basic Info"""

print(doge_df.describe())

"""# 2️⃣ Closing Price Trend"""

plt.figure(figsize=(10,5))
plt.plot(doge_df['Date'], doge_df['Close'])
plt.title('Dogecoin (DOGE-USD) Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price (USD)')
plt.grid(True)
plt.show()

"""# 3️⃣ Price Distribution"""

sns.histplot(doge_df['Close'], kde=True, bins=30)
plt.title('Distribution of Dogecoin Closing Prices')
plt.xlabel('Closing Price (USD)')
plt.show()

""" 4️⃣ Correlation Heatmap"""

plt.figure(figsize=(7,5))
sns.heatmap(doge_df[['Open', 'High', 'Low', 'Close', 'Volume']].corr(), annot=True, cmap='coolwarm')
plt.title('Dogecoin Price Feature Correlation')
plt.show()

""" Volume vs Price Scatter"""

sns.scatterplot(x='Volume', y='Close', data=doge_df)
plt.title('Dogecoin: Volume vs Closing Price')
plt.show()

from google.colab import files

files.download("cleaned_btc_data.csv")

files.download("cleaned_eth_data.csv")

files.download("cleaned_doge_data.csv")